version: '3.10'
services:
  crowdfunding:
    build: .
    ports:
      - "8085:8080"
    environment:
      - DATABASE_URL=${MYSQL_DATABASE_URL}
    depends_on:
      - db
  db:
    image: mysql:8.0.30
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    ports:
      - "3306:3306"

