version: '3.10'
services:
  myapp:
    build: .
    ports:
      - "8085:8080"
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=${MYSQL_database_url}
      - MYSQL_USER=${MYSQL_root}
    ports:
      - "3306:3306"
