version: '3.10'
services:
  myapp:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=databse_jee
      - MYSQL_USER=root
    ports:
      - "3306:3306"
